package com.medislot.app.data.ai

import kotlin.random.Random

object MockAiProvider {

    fun checkSymptoms(symptoms: String): SymptomCheckResponse {
        return SymptomCheckResponse(
            possibleConditions = listOf("Mild Viral Infection", "Seasonal Allergies", "Acute Rhino-sinusitis"),
            severity = "Mild",
            recommendedAction = "Schedule a primary care appointment if symptoms persist beyond 5 days.",
            homeCare = "Ensure adequate hydration, rest, and warm saline gargles. Over-the-counter antihistamines can relieve nasal congestion.",
            doctorVisitRecommendation = "Consult a doctor if you develop a persistent high fever or shortness of breath.",
            emergencyWarning = "Seek immediate emergency care if you experience chest pain, severe breathing difficulty, or bluish lips.",
            disclaimer = "This symptom check is for educational purposes only and does not replace professional clinical evaluation."
        )
    }

    fun explainReport(reportText: String): ReportExplanationResponse {
        return ReportExplanationResponse(
            summary = "The lab report indicates normal kidney function and blood sugar levels, with a slight elevation in total cholesterol.",
            normalFindings = listOf("Serum Creatinine: 0.9 mg/dL (Normal)", "Fasting Glucose: 92 mg/dL (Normal)", "Hemoglobin: 14.2 g/dL (Normal)"),
            abnormalFindings = listOf("Total Cholesterol: 228 mg/dL (Borderline High)", "LDL Cholesterol: 145 mg/dL (Elevated)"),
            possibleMeaning = "Elevated cholesterol suggests a potential benefit from dietary modifications, focusing on reducing saturated fats and increasing soluble fiber intake.",
            questionsToAskDoctor = listOf("Is medication needed for my cholesterol level?", "What specific dietary changes do you recommend first?", "When should I repeat this blood test?"),
            disclaimer = "This summary is generated by AI and must be verified by your healthcare provider before making any medical decisions."
        )
    }

    fun explainPrescription(prescriptionText: String): PrescriptionExplanationResponse {
        return PrescriptionExplanationResponse(
            summary = "This prescription includes a medication to manage blood pressure and a short-term pain reliever.",
            medicines = listOf(
                MedicineExplanation(
                    name = "Amlodipine 5mg",
                    purpose = "High blood pressure control",
                    howToTake = "Take 1 tablet daily in the morning, with or without food.",
                    commonSideEffects = listOf("Mild ankle swelling", "Headache", "Dizziness")
                ),
                MedicineExplanation(
                    name = "Ibuprofen 400mg",
                    purpose = "Pain and inflammation relief",
                    howToTake = "Take 1 tablet every 6 to 8 hours as needed for pain. Take with food.",
                    commonSideEffects = listOf("Stomach upset", "Heartburn", "Nausea")
                )
            ),
            generalPrecautions = listOf("Avoid consuming alcohol while taking these medications.", "Do not stop taking blood pressure medication abruptly without consulting your doctor."),
            disclaimer = "Always verify usage directions with your pharmacist or prescribing doctor."
        )
    }

    fun getDailyHealthTips(): DailyHealthTipsResponse {
        val index = Random.nextInt(3)
        return when (index) {
            0 -> DailyHealthTipsResponse(
                hydration = "Drink at least 8-10 glasses of water today to maintain kidney function and cellular energy.",
                exercise = "Incorporate 30 minutes of brisk walking or light jogging to boost cardiovascular health.",
                sleep = "Aim for 7 to 8 hours of quiet sleep tonight. Disconnect from screens 1 hour before bed.",
                nutrition = "Add a serving of leafy greens like spinach or kale to your lunch for essential micronutrients.",
                mentalWellness = "Spend 5 minutes doing deep diaphragmatic breathing to lower cortisol levels."
            )
            1 -> DailyHealthTipsResponse(
                hydration = "Start your morning with a tall glass of warm lemon water to stimulate metabolism.",
                exercise = "Do 15 minutes of light muscle stretching or yoga to relieve joint stiffness.",
                sleep = "Maintain a cool, dark room environment (around 68°F) for deep, uninterrupted REM cycles.",
                nutrition = "Swap processed snacks for a handful of raw almonds or walnuts to feed healthy brain fats.",
                mentalWellness = "Practice a 'gratitude check-in' - write down three things you are thankful for today."
            )
            else -> DailyHealthTipsResponse(
                hydration = "Keep a reusable water bottle at your desk to sip water consistently throughout the work day.",
                exercise = "Take the stairs instead of the elevator today to trigger active calf circulation.",
                sleep = "Avoid caffeine intake after 2:00 PM to protect your sleep latency and architecture.",
                nutrition = "Choose colorful berries as a natural dessert option, rich in protective cell antioxidants.",
                mentalWellness = "Take a 10-minute digital detox walk outdoors to refresh cognitive clarity."
            )
        }
    }

    fun getDietRecommendation(conditions: String, weight: String, bmi: String): DietRecommendationResponse {
        return DietRecommendationResponse(
            foodsToEat = listOf("High-fiber whole grains (Oats, Quinoa)", "Lean proteins (Grilled chicken, Tofu)", "Fresh vegetables (Broccoli, Brussels sprouts)", "Omega-3 rich foods (Salmon, Flaxseeds)"),
            foodsToAvoid = listOf("Refined sugars and sodas", "Deep-fried foods", "Highly processed meats", "Excessive sodium and table salt"),
            hydration = "Maintain a target intake of 2.7 to 3.2 liters of water daily.",
            lifestyleAdvice = listOf("Practice mindful eating and portion control.", "Avoid eating heavy meals within 3 hours of bedtime.", "Engage in moderate physical activity at least 150 minutes per week.")
        )
    }

    fun getAppointmentPrep(doctorName: String, specialty: String): AppointmentPrepResponse {
        return AppointmentPrepResponse(
            checklist = listOf(
                "Write down a timeline of your symptoms, noting when they started and what triggers them.",
                "Bring copies of recent lab tests, scans, or other medical records.",
                "Compile a complete list of current medications, vitamins, and supplements you take.",
                "Prepare a list of key questions you want to ask $doctorName.",
                "Note down any known allergies or chronic conditions in your family history."
            )
        )
    }

    fun chatWithAssistant(message: String): ChatResponse {
        return ChatResponse(
            reply = "I understand your concern about health optimization. Please monitor your daily vital levels and share them during your regular clinical check-ups. Let me know if you would like me to explain reports, compile a diet checklist, or guide you on symptom assessment.",
            suggestedQuestions = listOf("What are early signs of hypertension?", "How does diet affect BMI?", "Can you explain cholesterol reports?")
        )
    }

    fun generateConsultationSummary(rawNotes: String): ConsultationSummaryResponse {
        return ConsultationSummaryResponse(
            chiefComplaint = "Patient complains of occasional chest pressure and moderate fatigue.",
            history = "No prior history of cardiac events. Family history positive for hypertension.",
            diagnosis = "Essential Hypertension, suspected mild lifestyle fatigue.",
            treatment = "Initiate low-dose antihypertensive therapy and lifestyle modifications.",
            prescriptionSummary = "Amlodipine 5mg once daily.",
            followUp = "Return for BP check in 2 weeks.",
            patientInstructions = "Monitor blood pressure daily at home. Restrict dietary sodium to under 2000mg per day."
        )
    }

    fun generateSoapNote(rawNotes: String): SoapNoteResponse {
        return SoapNoteResponse(
            subjective = "Patient reports intermittent headaches and mild fatigue. Denies chest pain or dyspnea.",
            objective = "BP: 142/88 mmHg, HR: 74 bpm, Temp: 98.6 F. Clear breath sounds.",
            assessment = "Stage 1 Essential Hypertension. Fatigue likely secondary to sleep disruptions.",
            plan = "Start blood pressure monitoring protocol. Recommend sleep hygiene counseling and low-sodium diet."
        )
    }

    fun enhanceClinicalNotes(shorthandNotes: String): ClinicalEnhancementResponse {
        return ClinicalEnhancementResponse(
            enhancedNotes = "The patient presented with complaints of chronic headaches and fatigue. Vitals were notable for elevated blood pressure. A primary diagnosis of essential hypertension is established. Detailed treatment plans include starting low-sodium nutrition and home blood pressure logging, with a scheduled follow-up in two weeks."
        )
    }

    fun getDifferentialDiagnosis(symptoms: String): DiffDiagnosisResponse {
        return DiffDiagnosisResponse(
            possibleDiagnoses = listOf("Essential Hypertension", "Mild Obstructive Sleep Apnea", "Generalized Anxiety Disorder"),
            suggestedInvestigations = listOf("24-hour Ambulatory BP Monitoring", "Basic Metabolic Panel (BMP)", "Home Sleep Apnea Testing"),
            redFlags = listOf("Sudden severe headache", "Chest pain radiating to arm or jaw", "Shortness of breath at rest"),
            confidenceLevel = "Moderate",
            disclaimer = "This differential diagnosis is an AI assistance tool only and must not replace professional clinical decision making."
        )
    }

    fun draftPrescription(symptoms: String): PrescriptionDraftResponse {
        return PrescriptionDraftResponse(
            medicineCategories = listOf("Calcium Channel Blockers (e.g., Amlodipine)", "Angiotensin II Receptor Blockers (e.g., Losartan)"),
            lifestyleAdvice = listOf("Reduce dietary sodium intake", "Engage in moderate aerobic exercise", "Maintain structured sleep hygiene"),
            followUpRecommendations = "Schedule a clinical review in 14 days with a home BP log."
        )
    }

    fun interpretLabReport(testName: String): ReportInterpretationResponse {
        return ReportInterpretationResponse(
            summary = "The panel indicates borderline lipid levels with normal kidney and liver metrics.",
            abnormalValues = listOf("Total Cholesterol: 228 mg/dL (Elevated)", "LDL: 145 mg/dL (Elevated)"),
            criticalValues = emptyList(),
            recommendations = listOf("Implement low-fat nutrition and increase dietary fiber.", "Engage in active cardiovascular exercise 3-4 times a week."),
            possibleFollowUpTests = listOf("Lipid Panel follow-up in 3 months")
        )
    }

    fun interpretRadiologyReport(scanType: String): RadiologyReportResponse {
        return RadiologyReportResponse(
            summary = "Imaging shows clear lung fields and normal cardiac size. No acute cardiopulmonary abnormalities detected.",
            criticalFindings = emptyList(),
            recommendations = listOf("Routine age-appropriate screening guidelines.")
        )
    }

    fun generatePatientEducation(diagnosis: String): PatientEducationResponse {
        return PatientEducationResponse(
            instructions = "Hypertension means the force of blood against your artery walls is too high. Managing it requires taking medications regularly, reducing salt intake, staying active, and monitoring your blood pressure at home.",
            warningSigns = listOf("Severe chest pain", "Shortness of breath", "Sudden weakness or numbness on one side of the face/body")
        )
    }

    fun generateReferralLetter(patientName: String, age: Int, diagnosis: String): ReferralLetterResponse {
        return ReferralLetterResponse(
            letter = """
                Dear Specialist,
                
                I am writing to refer Mr./Ms. $patientName, age $age, who has been diagnosed with $diagnosis. The patient presents with elevated vital readings and mild persistent symptoms.
                
                I would appreciate your expert opinion and management recommendations for this case. Thank you for your clinical assistance.
                
                Sincerely,
                Referring Provider
            """.trimIndent()
        )
    }

    fun generateDischargeSummary(stayDetails: String): DischargeSummaryResponse {
        return DischargeSummaryResponse(
            letter = """
                DISCHARGE SUMMARY
                
                Patient stay details: $stayDetails
                Condition at Discharge: Clinically stable, vitals normalized.
                Discharge Instructions: Continue home monitoring of vital parameters. Follow up with your primary care provider in 7 days.
                
                Prescribed Meds: Standard maintenance medication.
            """.trimIndent()
        )
    }

    fun getOperationalInsights(): OperationalInsightsResponse {
        return OperationalInsightsResponse(
            summary = "Emergency department volume shows a seasonal increase, leading to a temporary bottleneck in patient triage.",
            bottlenecks = listOf("ED triage wait times", "ICU bed turnaround latency"),
            suggestedImprovements = listOf("Redistribute non-critical staff to triage desks during peak hours.", "Optimize discharge workflows to free up inpatient beds earlier."),
            priorityLevel = "Medium"
        )
    }

    fun optimizeResources(): ResourceOptimizationResponse {
        return ResourceOptimizationResponse(
            summary = "Critical care bed occupancy is high. Recommend coordinating with ward managers for early step-down discharges.",
            resourceAllocation = listOf("ICU beds: 85% capacity", "Ventilators: 60% capacity"),
            capacityPlanning = listOf("Active step-down candidate evaluations underway.")
        )
    }

    fun suggestStaffAllocation(): StaffAllocationResponse {
        return StaffAllocationResponse(
            additionalStaffing = "Deploy 2 additional triage nurses to the Emergency Department.",
            doctorRedistribution = "Reallocate 1 floating physician to support outpatient desks.",
            shiftOptimization = "Adjust shift change crossovers by 30 minutes to reduce handoff bottlenecks."
        )
    }

    fun predictEmergencyRisk(): EmergencyRiskResponse {
        return EmergencyRiskResponse(
            riskLevel = "Moderate",
            reason = "High intake volume in surrounding local clinics may redirect acute trauma flow.",
            recommendations = listOf("Prep trauma rooms 3 and 4.", "Alert call-back nurse rosters."),
            preparednessChecklist = listOf("Verify blood bank supply levels.", "Check emergency medicine reserve cart.")
        )
    }

    fun generatePerformanceReport(): PerformanceReportResponse {
        return PerformanceReportResponse(
            patientFlow = "Outpatient flow shows improved throughput following online bookings.",
            doctorEfficiency = "Average consultation durations are currently meeting optimal KPIs.",
            resourceUsage = "Diagnostic resource utilization is within target boundaries.",
            waitingTime = "Average waiting desk latency: 24 minutes.",
            capacity = "Active bed load: 78% total capacity.",
            improvementAreas = listOf("Reduce radiology scan transcription delay.")
        )
    }

    fun getDailyBriefing(): DailyBriefingResponse {
        return DailyBriefingResponse(
            todaySummary = "All operations are currently running smoothly. Shift handovers completed without critical incidents.",
            criticalAlerts = listOf("ED triage volume trending slightly high."),
            predictedBusyHours = "11:00 AM - 1:30 PM",
            recommendations = listOf("Ensure peak staff coverage at admissions.", "Verify backup nurse availability.")
        )
    }

    fun generateNotification(alertText: String): NotificationGeneratorResponse {
        return NotificationGeneratorResponse(
            notificationText = "Operational Update: High volume triage expected. Staff please verify backup rosters. Thank you."
        )
    }
}
